In [43]:
import numpy as np
import pandas as pd
import sklearn.preprocessing as pre_process
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split
from sklearn.utils import all_estimators
import sklearn.metrics as sm
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix,precision_score, recall_score, f1_score, roc_auc_score
import joblib

In [2]:
df=pd.read_csv("cleaned_data.csv")
df.head()

wins  losses  draws  height_cm  reach_in_cm    stance  \
0     7       0      0     190.50       182.88  Orthodox   
1    15      37      0     185.42       182.88  Orthodox   
2    13       9      0     177.80       182.88  Orthodox   
3     7       4      0     167.64       182.88  Orthodox   
4     8       2      0     190.50       193.04  Orthodox   

   significant_strikes_landed_per_minute  significant_striking_accuracy  \
0                                   0.00                              0   
1                                   3.36                             77   
2                                   0.00                              0   
3                                   1.40                             33   
4                                   2.05                             60   

   significant_strikes_absorbed_per_minute  significant_strike_defence  \
0                                     0.00                           0   
1                                     0.00                           0   
2                                     5.58                          60   
3                                     1.40                          75   
4                                     2.73                          42   

   average_takedowns_landed_per_15_minutes  takedown_accuracy  \
0                                     7.32                100   
1                                     0.00                  0   
2                                     0.00                  0   
3                                     0.00                  0   
4                                    10.23                100   

   takedown_defense  average_submissions_attempted_per_15_minutes  \
0                 0                                          21.9   
1               100                                          21.6   
2                 0                                          20.9   
3               100                                          20.9   
4                 0                                          20.4   

  match_results  
0           win  
1          loss  
2           win  
3           win  
4           win

In [10]:
X=df.iloc[:,3:14]
X

height_cm  reach_in_cm    stance  significant_strikes_landed_per_minute  \
0        190.50       182.88  Orthodox                                   0.00   
1        185.42       182.88  Orthodox                                   3.36   
2        177.80       182.88  Orthodox                                   0.00   
3        167.64       182.88  Orthodox                                   1.40   
4        190.50       193.04  Orthodox                                   2.05   
...         ...          ...       ...                                    ...   
4100     175.26       182.88  Orthodox                                   0.00   
4101     172.72       182.88  Orthodox                                   0.00   
4102     180.34       182.88  Orthodox                                   9.47   
4103     190.50       210.82  Southpaw                                   1.28   
4104     162.56       162.56  Southpaw                                   0.80   

      significant_striking_accuracy  significant_strikes_absorbed_per_minute  \
0                                 0                                     0.00   
1                                77                                     0.00   
2                                 0                                     5.58   
3                                33                                     1.40   
4                                60                                     2.73   
...                             ...                                      ...   
4100                              0                                     0.00   
4101                              0                                     0.00   
4102                             60                                    12.63   
4103                             33                                     2.55   
4104                             29                                     4.60   

      significant_strike_defence  average_takedowns_landed_per_15_minutes  \
0                              0                                     7.32   
1                              0                                     0.00   
2                             60                                     0.00   
3                             75                                     0.00   
4                             42                                    10.23   
...                          ...                                      ...   
4100                           0                                     0.00   
4101                           0                                     0.00   
4102                           0                                     0.00   
4103                          33                                     0.00   
4104                          42                                     2.00   

      takedown_accuracy  takedown_defense  \
0                   100                 0   
1                     0               100   
2                     0                 0   
3                     0               100   
4                   100                 0   
...                 ...               ...   
4100                  0                 0   
4101                  0                 0   
4102                  0               100   
4103                  0                 0   
4104                 18                 0   

      average_submissions_attempted_per_15_minutes  
0                                             21.9  
1                                             21.6  
2                                             20.9  
3                                             20.9  
4                                             20.4  
...                                            ...  
4100                                           0.0  
4101                                           0.0  
4102                                           0.0  
4103                                           0.0  
4104                   

In [8]:
#scalling and transforming
def trans_scale(X_to_trans,encoded_list,scale_list):
    ordinal_encoding=pre_process.OrdinalEncoder()
    standered_scalling=pre_process.StandardScaler()
    label_encoder=pre_process.LabelEncoder()
    transform_x=make_column_transformer( (ordinal_encoding ,encoded_list )
    ,(standered_scalling,scale_list))
    processed_x=transform_x.fit_transform(X)
    return processed_x

In [9]:
encoded_list=["stance"]
scale_list=['height_cm', 'reach_in_cm', 'significant_strikes_landed_per_minute', 'significant_striking_accuracy',
             'significant_strikes_absorbed_per_minute', 'significant_strike_defence', 'average_takedowns_landed_per_15_minutes',
               'takedown_accuracy', 'takedown_defense', 'average_submissions_attempted_per_15_minutes']
X=df.iloc[:,3:14]

processed_x=trans_scale(X,encoded_list,scale_list)
print(processed_x)


[[ 1.          1.43278238  0.07341207 ...  2.56647579 -1.13261143
  14.12993524]
 [ 1.          0.83943984  0.07341207 ... -0.9170325   1.77329925
  13.93081936]
 [ 1.         -0.05057398  0.07341207 ... -0.9170325  -1.13261143
  13.46621565]
 ...
 [ 1.          0.2460973   0.07341207 ... -0.9170325   1.77329925
  -0.40552378]
 [ 3.          1.43278238  3.65324158 ... -0.9170325  -1.13261143
  -0.40552378]
 [ 3.         -1.8306016  -2.5301003  ... -0.290001   -1.13261143
  -0.40552378]]


In [11]:
label_enco=pre_process.LabelEncoder()
Y=df["match_results"]
Y=np.c_[Y]
processed_y=label_enco.fit_transform(Y)
processed_y

c:\Users\Zain\anaconda3\envs\virtual_env\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 2, ..., 3, 3, 3])

In [15]:
train_x,test_x,train_y,test_y = train_test_split(processed_x , processed_y, test_size=0.2)

In [16]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(train_x,train_y)

LogisticRegression()

In [18]:
pred_y=model.predict(test_x)
pred_y


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [30]:
pred_y_Class=label_enco.inverse_transform(pred_y)
predicted_values=pd.DataFrame(pred_y_Class)
test_y_Class=label_enco.inverse_transform(test_y)
test_results=pd.DataFrame(test_y_Class)


0
0     win
1     win
2     win
3     win
4     win
..    ...
816   win
817   win
818   win
819  loss
820   win

[821 rows x 1 columns]

In [33]:
merged_frame = pd.concat([predicted_values, test_results], axis=1)
merged_frame.columns = ['Predicted', 'Actual']
merged_frame.to_csv("Results.csv")

In [50]:
model_test_acc=accuracy_score(test_y,pred_y)
model_test_f1=f1_score(test_y,pred_y,average='weighted')
model_test_precision=precision_score(test_y,pred_y,average='weighted')
model_test_recall=recall_score(test_y,pred_y,average='weighted')
conf_matrix=confusion_matrix(test_y,pred_y)


c:\Users\Zain\anaconda3\envs\virtual_env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [52]:
print(f"Accuracy: {model_test_acc}")
print(f"F1 Score: {model_test_f1}")
print(f"Precision: {model_test_precision}")
print(f"Recall: {model_test_recall}")
print() 
print()
print("Confusion Matrix") 
print(conf_matrix)
print()  

Accuracy: 0.8465286236297198
F1 Score: 0.7761707037238197
Precision: 0.7166107106244278
Recall: 0.8465286236297198


Confusion Matrix
[[  0   0  32   0]
 [  0   0  92   0]
 [  0   0 695   0]
 [  0   0   2   0]]



In [35]:
joblib.dump(model, 'model.pkl')

['model.pkl']